import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import ConvexClientProvider from "@/components/ConvexClientProvider";
import { Toaster } from "sonner";
import Header from "@/components/Header";
import { cn } from "@/lib/utils";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={cn("text-slate-900 antialiased light", inter.className)}
    >
      <body className="min-h-screen bg-zinc-50">
        <ConvexClientProvider>
          <Header />
          {children}
        </ConvexClientProvider>
        <Toaster richColors />
      </body>
    </html>
  );
}
